export enum StatusVinculo {
    PENDENTE_COLABORADOR = 'PENDENTE_COLABORADOR',
    APROVADO_COLABORADOR = 'APROVADO_COLABORADOR',
    REJEITADO_COLABORADOR = 'REJEITADO_COLABORADOR',
    DESLIGADO_COLABORADOR = 'DESLIGADO_COLABORADOR',
  
    PENDENTE_COORDENADOR = 'PENDENTE_COORDENADOR',
    APROVADO_COORDENADOR = 'APROVADO_COORDENADOR',
    REJEITADO_COORDENADOR = 'REJEITADO_COORDENADOR',
    DESLIGADO_COORDENADOR = 'DESLIGADO_COORDENADOR'
  }
  